maintainer        "Brian E"
maintainer_email  "private@private.com"
license           "Apache 2.0"
description       "Setup desktop environment on ubuntu"
version           "0.1"
depends           "apt"
supports          "ubuntu"
recipe            "deskotp_env", "Setup desktop environment on ubuntu"
